name: Deploy Vite App to S3

on:
  push:
    branches:
      - main # Trigger the workflow on pushes to the main branch

jobs:
  deploy:
    runs-on: self-hosted # Use a self-hosted runner
    steps:
      # Step 1: Checkout the repository
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20 # Use Node.js version 20

      # Step 3: Install unzip if Missing
      - name: Install unzip if Missing
        run: |
          if ! command -v unzip &> /dev/null; then
            echo "unzip not found. Installing..."
            sudo apt-get update
            sudo apt-get install -y unzip
          else
            echo "unzip is already installed."
          fi

      # Step 4: Check for AWS CLI and Install if Missing
      - name: Install AWS CLI if Missing
        run: |
          if ! command -v aws &> /dev/null; then
            echo "AWS CLI not found. Installing..."
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
          else
            echo "AWS CLI is already installed."
          fi

      # Step 5: Install dependencies
      - name: Install Dependencies
        run: npm install

      # Step 6: Build the Vite app
      - name: Build Vite App
        run: npm run build

      # Step 7: Sync the `dist` folder with the S3 bucket
      - name: Sync with S3 Bucket
        run: |
          aws s3 sync dist/ s3://retro-nft --delete
